#!/usr/bin/env python
"""Test script to verify the classification model is actually predicting"""

import os
import sys
import json
from pathlib import Path

# Add backend to path
sys.path.insert(0, str(Path(__file__).parent / "backend"))

# Load environment
from dotenv import load_dotenv
backend_dir = Path("backend")
env_file = backend_dir / ".env"
load_dotenv(env_file)

print("=" * 80)
print("CLASSIFICATION MODEL PREDICTION TEST")
print("=" * 80)

# Test 1: Check API key
api_key = os.getenv("GEMINI_API_KEY")
if not api_key:
    print("✗ GEMINI_API_KEY not found")
    sys.exit(1)
print(f"✓ GEMINI_API_KEY found: {api_key[:10]}...")

# Test 2: Import Gemini
try:
    import google.generativeai as genai
    print("✓ google-generativeai imported")
except ImportError as e:
    print(f"✗ Failed to import google-generativeai: {e}")
    sys.exit(1)

try:
    genai.configure(api_key=api_key)
    print("✓ Gemini configured")
except Exception as e:
    print(f"✗ Failed to configure Gemini: {e}")
    sys.exit(1)

# Test 3: Create model
try:
    model = genai.GenerativeModel("gemini-1.5-flash")
    print("✓ Gemini model created (gemini-1.5-flash)")
except Exception as e:
    print(f"✗ Failed to create model: {e}")
    sys.exit(1)

# Test 4: Test with human-written code
print("\n" + "-" * 80)
print("TEST 1: Human-written code (should be LOW AI probability)")
print("-" * 80)

human_code = """
def solve(arr):
    # First, I need to find the maximum
    max_val = arr[0]
    for i in range(len(arr)):
        if arr[i] > max_val:
            max_val = arr[i]
    
    # Then return it
    return max_val
"""

prompt_human = f"""
Analyze the following Python code snippet submitted by a student in a coding competition.
Tell me the probability (0-100) that this code was generated by an AI (like ChatGPT, Claude, etc).
AI code typically has perfect standard documentation, uses advanced concise idioms unnecessarily, or lacks typical human intermediate variable naming flaws.

Respond ONLY with a JSON object containing a "probability" key and a number value. Example: {{"probability": 85}}

Code:
```python
{human_code}
```
"""

try:
    print("Sending human code to Gemini...")
    response = model.generate_content(
        prompt_human,
        request_options={"timeout": 5.0}
    )
    text = response.text.strip()
    text = text.replace("```json", "").replace("```", "").strip()
    
    try:
        result = json.loads(text)
        prob = float(result.get("probability", 0))
        print(f"✓ Response: {prob}% AI probability")
        if prob < 50:
            print(f"✓ Correctly identified as HUMAN code (low probability)")
        else:
            print(f"⚠ Incorrectly identified as AI code (high probability)")
    except json.JSONDecodeError as e:
        print(f"✗ Response is NOT valid JSON: {e}")
        print(f"Response text:\n{text[:300]}")
        sys.exit(1)
        
except Exception as e:
    print(f"✗ Failed to analyze code: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)

# Test 5: Test with AI-generated code
print("\n" + "-" * 80)
print("TEST 2: AI-generated code (should be HIGH AI probability)")
print("-" * 80)

ai_code = """
def solve(arr):
    return max(arr) if arr else None
"""

prompt_ai = f"""
Analyze the following Python code snippet submitted by a student in a coding competition.
Tell me the probability (0-100) that this code was generated by an AI (like ChatGPT, Claude, etc).
AI code typically has perfect standard documentation, uses advanced concise idioms unnecessarily, or lacks typical human intermediate variable naming flaws.

Respond ONLY with a JSON object containing a "probability" key and a number value. Example: {{"probability": 85}}

Code:
```python
{ai_code}
```
"""

try:
    print("Sending AI code to Gemini...")
    response = model.generate_content(
        prompt_ai,
        request_options={"timeout": 5.0}
    )
    text = response.text.strip()
    text = text.replace("```json", "").replace("```", "").strip()
    
    try:
        result = json.loads(text)
        prob = float(result.get("probability", 0))
        print(f"✓ Response: {prob}% AI probability")
        if prob > 50:
            print(f"✓ Correctly identified as AI code (high probability)")
        else:
            print(f"⚠ Incorrectly identified as HUMAN code (low probability)")
    except json.JSONDecodeError as e:
        print(f"✗ Response is NOT valid JSON: {e}")
        print(f"Response text:\n{text[:300]}")
        sys.exit(1)
        
except Exception as e:
    print(f"✗ Failed to analyze code: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)

# Test 6: Test with medium complexity code
print("\n" + "-" * 80)
print("TEST 3: Medium complexity code (should be MEDIUM AI probability)")
print("-" * 80)

medium_code = """
def solve(nums):
    seen = set()
    for num in nums:
        if num in seen:
            return True
        seen.add(num)
    return False
"""

prompt_medium = f"""
Analyze the following Python code snippet submitted by a student in a coding competition.
Tell me the probability (0-100) that this code was generated by an AI (like ChatGPT, Claude, etc).
AI code typically has perfect standard documentation, uses advanced concise idioms unnecessarily, or lacks typical human intermediate variable naming flaws.

Respond ONLY with a JSON object containing a "probability" key and a number value. Example: {{"probability": 85}}

Code:
```python
{medium_code}
```
"""

try:
    print("Sending medium code to Gemini...")
    response = model.generate_content(
        prompt_medium,
        request_options={"timeout": 5.0}
    )
    text = response.text.strip()
    text = text.replace("```json", "").replace("```", "").strip()
    
    try:
        result = json.loads(text)
        prob = float(result.get("probability", 0))
        print(f"✓ Response: {prob}% AI probability")
        print(f"✓ Classification working (probability is between 0-100)")
    except json.JSONDecodeError as e:
        print(f"✗ Response is NOT valid JSON: {e}")
        print(f"Response text:\n{text[:300]}")
        sys.exit(1)
        
except Exception as e:
    print(f"✗ Failed to analyze code: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)

print("\n" + "=" * 80)
print("✓ CLASSIFICATION MODEL IS WORKING")
print("=" * 80)
print("\nNOTE: If you're always getting 'Human' in the app, the issue might be:")
print("1. The threshold for 'Human' classification is too high")
print("2. The IntegrityService is not being called properly")
print("3. The submission model is not storing the AI probability correctly")
