import logging
import os
import re
from sqlalchemy.orm import Session
from datetime import datetime

from ..models import Submission, Player

try:
    import google.generativeai as genai
    GEMINI_AVAILABLE = True
except ImportError:
    GEMINI_AVAILABLE = False

logger = logging.getLogger(__name__)

class IntegrityService:
    """Service for analyzing submission integrity (catching cheating/pasting)."""
    
    def __init__(self):
        self.gemini_available = GEMINI_AVAILABLE
        if self.gemini_available:
            self.api_key = os.getenv("GEMINI_API_KEY")
            if self.api_key:
                try:
                    genai.configure(api_key=self.api_key)
                    self.model = genai.GenerativeModel("gemini-1.5-flash")
                except Exception as e:
                    logger.error(f"Failed to initialize Gemini for IntegrityService: {e}")
                    self.gemini_available = False
            else:
                self.gemini_available = False

    def analyze_submission(self, db: Session, submission_id: str) -> None:
        """
        Analyze a submission to calculate cheat_probability and behavioral metrics.
        """
        logger.info(f"Running integrity analysis on {submission_id}")
        
        submission = db.query(Submission).filter(Submission.id == submission_id).first()
        if not submission:
            return

        code = submission.code
        
        # 1. Behavioral Heuristics (Basic calculation)
        submission.code_length = len(code)
        submission.code_lines = len(code.split('\n'))
        
        # Paste heuristic: high chars submitted in very little time
        # We don't have true frontend time_to_solve pushed yet, but if keystroke_speed is artificially provided or copy_paste_events > 0
        if submission.copy_paste_events > 0:
            submission.code_paste_probability = min(100.0, submission.copy_paste_events * 25.0)
        
        # 2. LLM Detection (Gemini)
        ai_prob = 0.0
        if self.gemini_available and self.api_key:
            try:
                prompt = f"""
                Analyze the following Python code snippet submitted by a student in a coding competition.
                Tell me the probability (0-100) that this code was generated by an AI (like ChatGPT, Claude, etc).
                AI code typically has perfect standard documentation, uses advanced concise idioms unnecessarily, or lacks typical human intermediate variable naming flaws.
                
                Respond ONLY with a JSON object containing a "probability" key and a number value. Example: {{"probability": 85}}
                
                Code:
                ```python
                {code[:2000]}
                ```
                """
                
                response = self.model.generate_content(prompt)
                
                # Parse JSON
                text = response.text.replace("```json", "").replace("```", "").strip()
                import json
                result = json.loads(text)
                if "probability" in result:
                    ai_prob = float(result["probability"])
                    submission.ai_quality_score = ai_prob # Store AI probability
            except Exception as e:
                logger.error(f"Gemini integrity analysis failed: {e}")
        
        # 3. Aggregate Cheat Probability
        # Base it on paste detection and AI probability
        paste_prob = submission.code_paste_probability or 0.0
        
        overall = (paste_prob * 0.4) + (ai_prob * 0.6)
        submission.cheat_probability = min(100.0, overall)
        
        db.commit()
        logger.info(f"Integrity analysis complete for {submission_id} (Cheat Prob: {overall}%)")