import logging
import os
import re
from sqlalchemy.orm import Session
from datetime import datetime

from ..models import Submission, Player

try:
    import anthropic
    ANTHROPIC_AVAILABLE = True
except ImportError:
    ANTHROPIC_AVAILABLE = False

try:
    import google.generativeai as genai
    GEMINI_AVAILABLE = True
except ImportError:
    GEMINI_AVAILABLE = False

logger = logging.getLogger(__name__)

class IntegrityService:
    """Service for analyzing submission integrity (catching cheating/pasting)."""
    
    def __init__(self):
        self.provider = os.getenv("AI_PROVIDER", "gemini").lower()
        self.client = None
        self.model = None

        if self.provider == "gemini":
            self.ai_available = GEMINI_AVAILABLE
            if self.ai_available:
                self.api_key = os.getenv("GEMINI_API_KEY")
                if self.api_key:
                    try:
                        genai.configure(api_key=self.api_key)
                        self.model = genai.GenerativeModel("gemini-1.5-flash")
                    except Exception as e:
                        logger.error(f"Failed to initialize Gemini for IntegrityService: {e}")
                        self.ai_available = False
                else:
                    self.ai_available = False
        else:
            self.ai_available = ANTHROPIC_AVAILABLE
            if self.ai_available:
                self.api_key = os.getenv("ANTHROPIC_API_KEY")
                if self.api_key:
                    try:
                        self.client = anthropic.Anthropic(api_key=self.api_key)
                    except Exception as e:
                        logger.error(f"Failed to initialize Anthropic for IntegrityService: {e}")
                        self.ai_available = False
                else:
                    self.ai_available = False

    def analyze_submission(self, db: Session, submission_id: str) -> None:
        """
        Analyze a submission to calculate cheat_probability and behavioral metrics.
        """
        logger.info(f"Running integrity analysis on {submission_id}")
        
        submission = db.query(Submission).filter(Submission.id == submission_id).first()
        if not submission:
            return

        code = submission.code
        
        # 1. Behavioral Heuristics (Basic calculation)
        submission.code_length = len(code)
        submission.code_lines = len(code.split('\n'))
        
        # Space Complexity Heuristic (Simple estimate based on variable count/types)
        # Using a base 0.1MB + factor of length
        submission.memory_used_mb = 0.1 + (len(code) / 10000.0)

        # Time Complexity Heuristic (Nested loops detection)
        loops = len(re.findall(r'\b(for|while)\b', code))
        nested_loops = len(re.findall(r'(\bfor\b|\bwhile\b).*\n\s+(\bfor\b|\bwhile\b)', code))
        recursion = 1 if re.search(r'def\s+(\w+)\(.*\).* \1\(', code, re.DOTALL) else 0
        
        # Calculate a "goodness" score (0-100)
        # More loops/recursion reduces the score
        complexity_impact = (loops * 10) + (nested_loops * 20) + (recursion * 30)
        submission.complexity_score = max(0, min(100, 100 - complexity_impact))

        # Paste heuristic: high chars submitted in very little time
        # We don't have true frontend time_to_solve pushed yet, but if keystroke_speed is artificially provided or copy_paste_events > 0
        if submission.copy_paste_events > 0:
            submission.code_paste_probability = min(100.0, submission.copy_paste_events * 25.0)
        
        # 2. LLM Detection (Gemini/Anthropic)
        ai_prob = 0.0
        if self.ai_available and self.api_key:
            try:
                prompt = f"""
                Analyze the following Python code snippet submitted by a student in a coding competition.
                Tell me the probability (0-100) that this code was generated by an AI (like ChatGPT, Claude, etc).
                AI code typically has perfect standard documentation, uses advanced concise idioms unnecessarily, or lacks typical human intermediate variable naming flaws.
                
                Respond ONLY with a JSON object containing a "probability" key and a number value. Example: {{"probability": 85}}
                
                Code:
                ```python
                {code[:2000]}
                ```
                """
                
                if self.provider == "gemini":
                    # Short timeout for integrity check to prevent hangs
                    response = self.model.generate_content(
                        prompt,
                        request_options={"timeout": 5.0} # 5 second timeout
                    )
                    text = response.text
                else:
                    response = self.client.messages.create(
                        model="claude-3-5-sonnet-20241022",
                        max_tokens=1000,
                        temperature=0.0,
                        messages=[{"role": "user", "content": prompt}],
                        timeout=5.0
                    )
                    text = response.content[0].text
                
                # Parse JSON
                text = text.replace("```json", "").replace("```", "").strip()
                import json
                result = json.loads(text)
                if "probability" in result:
                    ai_prob = float(result["probability"])
                    submission.ai_quality_score = ai_prob # Store AI probability
            except Exception as e:
                logger.error(f"Integrity analysis AI call failed (provider: {self.provider}): {e}")
                # Fallback to behavioral metrics only; don't raise to avoid blocking commits
        
        # 3. Aggregate Cheat Probability
        # Base it on paste detection and AI probability
        paste_prob = submission.code_paste_probability or 0.0
        
        overall = (paste_prob * 0.4) + (ai_prob * 0.6)
        submission.cheat_probability = min(100.0, overall)
        
        db.commit()
        logger.info(f"Integrity analysis complete for {submission_id} (Cheat Prob: {overall}%)")